'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VendingMachine.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0001226_6604_ph_pee_wee_crunchy_bbq_flavored_snack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0001226_6604_ph-pee-wee-crunchy-bbq-flavored-snack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _121051_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("121051_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _13ec2b7081464ea49c91ab5e7ee1bb07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("13ec2b7081464ea49c91ab5e7ee1bb07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _14210011cda8a72ecf54ebf67b607dc5_quarter_dollar_illustration_tail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("14210011cda8a72ecf54ebf67b607dc5-quarter-dollar-illustration-tail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1671643479_220879() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1671643479_220879", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1999_Obverse_Proof() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1999_Obverse_Proof", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _379c2752_122f_4016_9ed7_707d57784b19_256x256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("379c2752-122f-4016-9ed7-707d57784b19_256x256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _58718a4a7b7f6103e35c6ce4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("58718a4a7b7f6103e35c6ce4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6288d08f74f0826429bc77d875a9461e() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6288d08f74f0826429bc77d875a9461e", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property c89cdf1987a8bf2aeb0ff9ea92001707_large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c89cdf1987a8bf2aeb0ff9ea92001707_large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property c89cdf1987a8bf2aeb0ff9ea92001707_large1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c89cdf1987a8bf2aeb0ff9ea92001707_large1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cho0336bd465c4_5aea_45cb_bbea_31e7a8fba060300x300png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cho0336bd465c4-5aea-45cb-bbea-31e7a8fba060300x300png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dingdong4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dingdong4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FLAMIN__HOT_2024_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FLAMIN' HOT 2024.1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_of_happy_sun_ice_cream_pork_skins() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-of-happy-sun-ice-cream-pork-skins", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pepperoni_Pizza_Rolls_460x460() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pepperoni-Pizza-Rolls_460x460", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngtree_toasted_bread_with_jam_snack_picture_image_13137955() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngtree-toasted-bread-with-jam-snack-picture-image_13137955", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Presidential_dollar_coin_reverse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Presidential_dollar_coin_reverse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Presidential_dollar_coin_reverse1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Presidential_dollar_coin_reverse1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property purepng_com_lays_potato_chips_packfood_potato_tasty_pack_lays_chips_taste_product_snaks_941524625368gdogh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("purepng.com-lays-potato-chips-packfood-potato-tasty-pack-lays-chips-taste-product"& _ 
                        "-snaks-941524625368gdogh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SS1_New_putwfxm0rraoaja5xieuw7soinbg3bki3epcu9yux6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SS1_New-putwfxm0rraoaja5xieuw7soinbg3bki3epcu9yux6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property US_Nickel_2013_Rev() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("US_Nickel_2013_Rev", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
